dist: xenial
sudo: false
language: scala
scala:
  - 2.12.8
jdk:
  - openjdk11
before_script:
  - "cd orchard-server"
script:
  - "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
