sudo: false
language: scala
scala:
  - 2.12.6
jdk:
  - oraclejdk8
before_script:
  - "cd selfouettie-server"
script:
  - "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
